# Generated by Django 4.0 on 2021-12-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArea', models.IntegerField()),
                ('DscArea', models.CharField(max_length=42)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='TblArtigoPublicado',
            fields=[
                ('CodArtigoPublicado', models.AutoField(primary_key=True, serialize=False)),
                ('ART', models.CharField(max_length=255)),
                ('TipArtigoRelevancia', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3)),
                ('TipArtigoDivulgacaoCientifica', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3)),
                ('AnoPublicacaoArtigo', models.CharField(db_index=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Artigo Publicado',
                'verbose_name_plural': 'Artigos Publicados',
            },
        ),
        migrations.CreateModel(
            name='TblCargos',
            fields=[
                ('CodCargo', models.AutoField(primary_key=True, serialize=False)),
                ('DscCargo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='TblGrandeArea',
            fields=[
                ('CodGrandeArea', models.AutoField(primary_key=True, serialize=False)),
                ('DscGrandeArea', models.CharField(max_length=27)),
            ],
            options={
                'verbose_name': 'Grande Áera',
                'verbose_name_plural': 'Grandes Áeras',
            },
        ),
        migrations.CreateModel(
            name='TblIssn',
            fields=[
                ('CodIssn', models.AutoField(primary_key=True, serialize=False)),
                ('DscIssn', models.CharField(max_length=20)),
                ('DscIssnTituloJornal', models.CharField(max_length=195)),
            ],
            options={
                'verbose_name': 'ISSN',
                'verbose_name_plural': 'ISSNs',
            },
        ),
        migrations.CreateModel(
            name='TblOrgaoIeExerc',
            fields=[
                ('codSiglaOrgaoIE', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código da IE')),
                ('nomOrgaoIEExerc', models.CharField(max_length=50, verbose_name='Nome da IE')),
            ],
            options={
                'verbose_name': 'Instituição de Ensino de Exercício',
                'verbose_name_plural': 'Instituições de Ensino de Exercício',
            },
        ),
        migrations.CreateModel(
            name='TblPalavraChaveArt',
            fields=[
                ('CodPalavrasChavesArtigos', models.AutoField(primary_key=True, serialize=False)),
                ('DscArtigoPalavrasChave', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Plavra chave',
                'verbose_name_plural': 'Plavras chaves',
            },
        ),
        migrations.CreateModel(
            name='TblSituacao',
            fields=[
                ('CodSituacao', models.AutoField(primary_key=True, serialize=False)),
                ('DscSituacao', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='TblTitulosArtigos',
            fields=[
                ('CodTitulosArtigos', models.AutoField(primary_key=True, serialize=False)),
                ('DscTitulosArtigos', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Titulo de Artigo',
                'verbose_name_plural': 'Titulos de Artigos',
            },
        ),
        migrations.CreateModel(
            name='TblSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodSubArea', models.IntegerField()),
                ('DscSubArea', models.CharField(max_length=64)),
                ('CodArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblarea')),
                ('CodGrandeArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblgrandearea')),
            ],
            options={
                'verbose_name': 'Sub Área',
                'verbose_name_plural': 'Sub Áreas',
            },
        ),
        migrations.CreateModel(
            name='TblServidores',
            fields=[
                ('CodServidor', models.AutoField(primary_key=True, serialize=False)),
                ('CodServidorPortalTransp', models.CharField(max_length=8)),
                ('NomServidor', models.CharField(max_length=60)),
                ('NumCpf', models.CharField(max_length=14)),
                ('NumSiap', models.CharField(max_length=7)),
                ('CodCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tblcargos')),
                ('CodSiglaOrgaoIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tblorgaoieexerc')),
            ],
        ),
        migrations.CreateModel(
            name='TblEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodEspecialidade', models.IntegerField()),
                ('DscEspecialidade', models.CharField(max_length=85)),
                ('CodArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblarea')),
                ('CodGrandeArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblgrandearea')),
                ('CodSubArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblsubarea')),
            ],
            options={
                'verbose_name': 'Sub Área',
                'verbose_name_plural': 'Sub Áreas',
            },
        ),
        migrations.CreateModel(
            name='TblArtigoPublicadoPalavrasChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArtigoPublicado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblartigopublicado')),
                ('CodPalavrasChavesArtigos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblpalavrachaveart')),
            ],
            options={
                'verbose_name': 'Artigo Publicado - Palavra-Chave',
                'verbose_name_plural': 'Artigos Publicados - Palavras-Chaves',
            },
        ),
        migrations.CreateModel(
            name='TblArtigoPublicadoAreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblarea')),
                ('CodArtigoPublicado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblartigopublicado')),
                ('CodGrandeArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblgrandearea')),
            ],
            options={
                'verbose_name': 'Artigo publicado por área do conhecimento',
                'verbose_name_plural': 'Artigos publicados por área do conhecimento',
            },
        ),
        migrations.AddField(
            model_name='tblartigopublicado',
            name='CodIssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblissn'),
        ),
        migrations.AddField(
            model_name='tblartigopublicado',
            name='CodSiglaAtuacaoProfissionalLattes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblorgaoieexerc'),
        ),
        migrations.AddField(
            model_name='tblartigopublicado',
            name='CodTitulosArtigos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tbltitulosartigos'),
        ),
        migrations.AddField(
            model_name='tblarea',
            name='CodGrandeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tblgrandearea'),
        ),
        migrations.AddConstraint(
            model_name='tblsubarea',
            constraint=models.UniqueConstraint(fields=('CodGrandeArea', 'CodArea', 'CodSubArea'), name='CodGrandeArea_CodArea_CodSubArea'),
        ),
        migrations.AddConstraint(
            model_name='tblespecialidade',
            constraint=models.UniqueConstraint(fields=('CodGrandeArea', 'CodArea', 'CodSubArea', 'CodEspecialidade'), name='CodGrandeArea_CodArea_CodSubArea_CodEspecialidade'),
        ),
        migrations.AddConstraint(
            model_name='tblarea',
            constraint=models.UniqueConstraint(fields=('CodGrandeArea', 'CodArea'), name='CodGrandeArea_CodArea'),
        ),
    ]
