# Generated by Django 4.0 on 2022-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_codsiglaorgaoie_tblorgaoieexerc_codsiglaorgaoie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblarea',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tblespecialidade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tblsubarea',
            name='id',
        ),
        migrations.AlterField(
            model_name='tblarea',
            name='CodArea',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblespecialidade',
            name='CodEspecialidade',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblsubarea',
            name='CodSubArea',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
